# Generated by Django 4.0.2 on 2022-02-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('ahorro a la mano', 'Ahorro a la mano'), ('bancolombia', 'Bancolombia'), ('davivienda', 'Davivienda SAS')], max_length=100, null=True)),
                ('otros_detalles', models.CharField(blank=True, max_length=55, null=True)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Forma de pagos',
                'db_table': 'appConfiguracionFormaPago',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=80, null=True)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'db_table': 'appConfiguracionRubro',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(blank=True, max_length=55, null=True)),
                ('stock_minimo', models.CharField(blank=True, max_length=100, null=True)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stocks',
                'db_table': 'appConfiguracionStock',
            },
        ),
        migrations.CreateModel(
            name='TipoIndetificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=70, null=True)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipos de indentificaciones',
                'db_table': 'appConfiguracionTipoIdentificacion',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=55, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=30, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('obj_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appConfiguracion.stock')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'appConfiguracionIngredientes',
            },
        ),
    ]
