# Generated by Django 4.0.2 on 2022-02-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appConfiguracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('iva', models.FloatField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'appFacturaFactura',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=80, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('precio_sin_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tamanio', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=60)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('obj_rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appConfiguracion.rubro')),
                ('obj_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appConfiguracion.stock')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'appFacturaProducto',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('obj_ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appConfiguracion.ingrediente')),
                ('obj_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appFactura.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'appFacturaReceta',
            },
        ),
    ]
