# Generated by Django 4.0.2 on 2022-02-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appFactura', '0001_initial'),
        ('appConfiguracion', '0001_initial'),
        ('appPersona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='obj_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appPersona.cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='obj_forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appConfiguracion.formapago'),
        ),
    ]
