# Generated by Django 4.0.2 on 2022-02-11 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appConfiguracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroIdentificacion', models.CharField(blank=True, max_length=60, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('rol_persona', models.CharField(blank=True, max_length=60, null=True)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('obj_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipoIdentificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appConfiguracion.tipoindetificacion')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'appPersonaPersona',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=55, null=True)),
                ('numeroIdentificacion', models.CharField(blank=True, max_length=60, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('sys_active', models.BooleanField(default=True)),
                ('sys_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('sys_fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('tipoIdentificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appConfiguracion.tipoindetificacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'appPersonaCliente',
            },
        ),
    ]
